spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/Nisanth #Keycloak instance(realm) name
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs #validate jwt token


server:
  port: 9191
jwt:
  auth:
    converter:
      resource-id: nisanth-rest-api
      principle-attribute: preferred_username
  main:
    allow-bean-definition-overriding: true
